"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var environment_1 = require("../../environment");
var ndarray_1 = require("../../math/ndarray");
var graph_1 = require("../graph");
var tensor_array_map_1 = require("../tensor_array_map");
var multiply_1 = require("./multiply");
describe('divide operation', function () {
    var math = environment_1.ENV.math;
    var x1Tensor;
    var x2Tensor;
    var yTensor;
    var multiplyOp;
    var activations;
    var gradients;
    beforeEach(function () {
        activations = new tensor_array_map_1.TensorArrayMap();
        gradients = new tensor_array_map_1.SummedTensorArrayMap(math);
    });
    afterEach(function () {
        activations.disposeArray(x1Tensor);
        activations.disposeArray(x2Tensor);
        activations.disposeArray(yTensor);
        gradients.disposeArray(x1Tensor);
        gradients.disposeArray(x2Tensor);
        gradients.disposeArray(yTensor);
    });
    it('element wise multiply', function () {
        var x1 = ndarray_1.Array1D.new([1, 2, 3]);
        var x2 = ndarray_1.Array1D.new([2, 4, 6]);
        x1Tensor = new graph_1.Tensor(x1.shape);
        x2Tensor = new graph_1.Tensor(x2.shape);
        yTensor = new graph_1.Tensor(x2.shape);
        activations.set(x1Tensor, x1);
        activations.set(x2Tensor, x2);
        multiplyOp = new multiply_1.Multiply(x1Tensor, x2Tensor, yTensor);
        multiplyOp.feedForward(math, activations);
        var y = activations.get(yTensor);
        expect(y.get(0)).toEqual(1 * 2);
        expect(y.get(1)).toEqual(2 * 4);
        expect(y.get(2)).toEqual(3 * 6);
        var dy = ndarray_1.Array1D.new([3, 4, 5]);
        gradients.add(yTensor, dy);
        multiplyOp.backProp(math, activations, gradients);
        var dx1 = gradients.get(x1Tensor);
        expect(dx1.get(0)).toEqual(x2.get(0) * dy.get(0));
        expect(dx1.get(1)).toEqual(x2.get(1) * dy.get(1));
        expect(dx1.get(2)).toEqual(x2.get(2) * dy.get(2));
        var dx2 = gradients.get(x2Tensor);
        expect(dx2.get(0)).toEqual(x1.get(0) * dy.get(0));
        expect(dx2.get(1)).toEqual(x1.get(1) * dy.get(1));
        expect(dx2.get(2)).toEqual(x1.get(2) * dy.get(2));
    });
    it('scalar times ndarray', function () {
        var x1 = ndarray_1.Scalar.new(2);
        var x2 = ndarray_1.Array1D.new([2, 4, 6]);
        x1Tensor = new graph_1.Tensor(x1.shape);
        x2Tensor = new graph_1.Tensor(x2.shape);
        yTensor = new graph_1.Tensor(x2.shape);
        activations.set(x1Tensor, x1);
        activations.set(x2Tensor, x2);
        multiplyOp = new multiply_1.Multiply(x1Tensor, x2Tensor, yTensor);
        multiplyOp.feedForward(math, activations);
        var y = activations.get(yTensor);
        expect(y.get(0)).toEqual(2 * 2);
        expect(y.get(1)).toEqual(2 * 4);
        expect(y.get(2)).toEqual(2 * 6);
        var dy = ndarray_1.Array1D.new([3, 4, 5]);
        gradients.add(yTensor, dy);
        multiplyOp.backProp(math, activations, gradients);
        var dx1 = gradients.get(x1Tensor).asScalar();
        expect(dx1.get()).toEqual(x2.get(0) * dy.get(0) + x2.get(1) * dy.get(1) + x2.get(2) * dy.get(2));
        var dx2 = gradients.get(x2Tensor);
        expect(dx2.get(0)).toEqual(x1.get() * dy.get(0));
        expect(dx2.get(1)).toEqual(x1.get() * dy.get(1));
        expect(dx2.get(2)).toEqual(x1.get() * dy.get(2));
    });
    it('ndarray times scalar', function () {
        var x1 = ndarray_1.Array1D.new([2, 4, 6]);
        var x2 = ndarray_1.Scalar.new(2);
        x1Tensor = new graph_1.Tensor(x1.shape);
        x2Tensor = new graph_1.Tensor(x2.shape);
        yTensor = new graph_1.Tensor(x2.shape);
        activations.set(x1Tensor, x1);
        activations.set(x2Tensor, x2);
        multiplyOp = new multiply_1.Multiply(x1Tensor, x2Tensor, yTensor);
        multiplyOp.feedForward(math, activations);
        var y = activations.get(yTensor);
        expect(y.get(0)).toEqual(2 * 2);
        expect(y.get(1)).toEqual(2 * 4);
        expect(y.get(2)).toEqual(2 * 6);
        var dy = ndarray_1.Array1D.new([3, 4, 5]);
        gradients.add(yTensor, dy);
        multiplyOp.backProp(math, activations, gradients);
        var dx1 = gradients.get(x1Tensor);
        expect(dx1.get(0)).toEqual(x2.get() * dy.get(0));
        expect(dx1.get(1)).toEqual(x2.get() * dy.get(1));
        expect(dx1.get(2)).toEqual(x2.get() * dy.get(2));
        var dx2 = gradients.get(x2Tensor).asScalar();
        expect(dx2.get()).toEqual(x1.get(0) * dy.get(0) + x1.get(1) * dy.get(1) + x1.get(2) * dy.get(2));
    });
});
//# sourceMappingURL=multiply_test.js.map